<?php 
//根据域名列表得出IP
//$dm = 'www.prykweb.com';
$dm=array(
				'www.purui.cn',
				'www.p0931.com',
				'www.p028.com',
				'www.p0371.com',
				'www.p0551.com',
				'www.kmprykyy.com',
				'www.p0991.com',
				'www.pr0791.com',
				'www.pr021.com',
				'www.p023.com',
				'www.pr027.com',
				'www.p0451.com',
				'www.bjpryk.com',
				' ',
				'www.lzpryk.com',
				'mob.p0931.com',
				'm.p0931.com',
				' ',
				'www.prykyy028.com',
				'www.puruiybn.com',
				'www.puruiybc.com',
				'www.prykyy028.com',
				'www.purui028.com',
				'www.cdpryk.com',
				'mob.purui028.com',
				'mob.p028.com',
				' ',
				'www.zzpr0371.com',
				'www.zzpryk.com',
				'www.prykyy0371.com',
				'www.hneyes.com',
				'mob.p0371.com',
				'm.p0371.com',
				'm.zzpr0371.com',
				' ',
				'www.prykyy0551.com',
				'www.ifs150.com',
				'www.hfpryk.com',
				'www.hfpr120.com',
				'www.yanke0551.com',
				'wap.yanke0551.com',
				'wap.purui0551.com',
				'wap.ifs150.com',
				'wap.hfpryk.com',
				'wap.hfpr120.com',
				'wap.p0551.com',
				'mob.p0551.com',
				' ',
				'www.purui0871.com',
				'www.ynyanke.com',
				'www.puruiykb.com',
				'www.ynjinshi.com',
				'www.prykyy0871.com',
				'www.pryk0871.com',
				'mob.kmprykyy.com',
				'm.ynyanke.com',
				'm.ynjinshi.com',
				'm.pryk0871.com',
				'm.kmprykyy.com',	
				' ',
				'www.wlmqpryk.com',
				'www.puruiykx.com',
				'm.p0991.com',
				' ',
				'www.pr0791.cn',
				'www.p0791.net',
				'www.prykyy0791.com',
				'www.puruiybx.com',
				'www.puruiybs.com',
				'mob.pr0791.com',
				'm.pr0791.com',
				' ',
				'www.shpryk.com',
				'www.purui021.com',
				'www.puruiybb.com',
				'wap.pryk021.com',
				'shyy.pr021.com',
				'shtj.pr021.com',
				'mob.pr021.com',
				' ',
				'www.purui023.com',
				'www.puruiybl.com',
				'www.prykyy023.com',
				'www.cqprykyy.com',
				'www.cqpryk.com',
				'www.cqpr023.com',
				'mob.p023.com',
				'm.p023.com',	
				' ',
				'www.purui027.com',
				'www.027pryk.com',
				'mob.027pryk.com',
				'mob.pr027.com',
				'm.pr027.com',
				' ',
				'www.hrbpryk.com',
				'www.puruiykz.com',
				'm.p0451.com',
				'w.p0451.com',
				'4g.p0451.com',
				' ',
				'www.purui010.com',
				'www.puruiykh.com',
				'www.5i5eye.com',
				'm.bjpryk.com',
				'm.puruiykh.com',
				' ',
				'www.prykweb.com',
				'web.prykweb.com',
				'abc.prykweb.com',
				'new.prykweb.com',
				'ai.purui.cn',
				'gd.purui.cn',
				'zhaopin.purui.cn',
				'weixin.purui.cn',
				' ',
				);				
foreach($dm as $v){
	echo $v.'  IP IS:   <font color=\'red\'>'.gethostbyname($v).'</font><br /><hr>';
}

